FROM node:24-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /workspace
COPY package.json pnpm-lock.yaml tsconfig.base.json nx.json jest.preset.js ./
RUN pnpm install --frozen-lockfile --ignore-scripts
