import type { ReportLocale } from "./exports.types.js";

interface ReportStrings {
  title: string;
  header: {
    partner: string;
    property: string;
    period: string;
    generatedAt: string;
    currencyNote: string;
    allProperties: string;
  };
  totals: {
    gross: string;
    taxes: string;
    commission: string;
    net: string;
    count: string;
  };
  columns: {
    date: string;
    reservation: string;
    property: string;
    method: string;
    reference: string;
    nights: string;
    rate: string;
    subtotal: string;
    taxes: string;
    total: string;
    commission: string;
    net: string;
  };
  footer: {
    pageOf: (current: number, total: number) => string;
    generatedBy: string;
  };
  empty: string;
  sheets: {
    summary: string;
    detail: string;
  };
  disbursement: {
    title: string;
    columns: {
      month: string;
      scheduledFor: string;
      status: string;
      paidAt: string;
      reference: string;
      gross: string;
      commission: string;
      net: string;
      payments: string;
    };
    status: {
      paid: string;
      pending: string;
      projected: string;
      failed: string;
    };
    empty: string;
    sheets: {
      summary: string;
      months: string;
    };
  };
}

const ES: ReportStrings = {
  title: "Reporte de pagos",
  header: {
    partner: "Socio",
    property: "Propiedad",
    period: "Período",
    generatedAt: "Generado",
    currencyNote: "Valores en USD",
    allProperties: "Todas las propiedades",
  },
  totals: {
    gross: "Bruto",
    taxes: "Impuestos retenidos",
    commission: "Comisión TravelHub",
    net: "Valor neto",
    count: "Pagos",
  },
  columns: {
    date: "Fecha",
    reservation: "# Reserva",
    property: "Propiedad",
    method: "Método",
    reference: "# Referencia",
    nights: "Noches",
    rate: "Tarifa",
    subtotal: "Subtotal",
    taxes: "Impuestos",
    total: "Total pagado",
    commission: "Comisión",
    net: "Neto",
  },
  footer: {
    pageOf: (c, t) => `Página ${c} de ${t}`,
    generatedBy: "Generado por TravelHub",
  },
  empty: "Sin pagos en este período",
  sheets: { summary: "Resumen", detail: "Detalle" },
  disbursement: {
    title: "Reporte de desembolsos",
    columns: {
      month: "Mes",
      scheduledFor: "Programado",
      status: "Estado",
      paidAt: "Pagado",
      reference: "Referencia",
      gross: "Bruto",
      commission: "Comisión",
      net: "Neto",
      payments: "Pagos",
    },
    status: {
      paid: "Pagado",
      pending: "Pendiente",
      projected: "Proyectado",
      failed: "Fallido",
    },
    empty: "Sin desembolsos en este período",
    sheets: { summary: "Resumen", months: "Meses" },
  },
};

const EN: ReportStrings = {
  title: "Payments report",
  header: {
    partner: "Partner",
    property: "Property",
    period: "Period",
    generatedAt: "Generated",
    currencyNote: "Values in USD",
    allProperties: "All properties",
  },
  totals: {
    gross: "Gross",
    taxes: "Taxes withheld",
    commission: "TravelHub commission",
    net: "Net value",
    count: "Payments",
  },
  columns: {
    date: "Date",
    reservation: "Reservation",
    property: "Property",
    method: "Method",
    reference: "Reference",
    nights: "Nights",
    rate: "Rate",
    subtotal: "Subtotal",
    taxes: "Taxes",
    total: "Total paid",
    commission: "Commission",
    net: "Net",
  },
  footer: {
    pageOf: (c, t) => `Page ${c} of ${t}`,
    generatedBy: "Generated by TravelHub",
  },
  empty: "No payments in this period",
  sheets: { summary: "Summary", detail: "Detail" },
  disbursement: {
    title: "Disbursements report",
    columns: {
      month: "Month",
      scheduledFor: "Scheduled",
      status: "Status",
      paidAt: "Paid at",
      reference: "Reference",
      gross: "Gross",
      commission: "Commission",
      net: "Net",
      payments: "Payments",
    },
    status: {
      paid: "Paid",
      pending: "Pending",
      projected: "Projected",
      failed: "Failed",
    },
    empty: "No disbursements in this period",
    sheets: { summary: "Summary", months: "Months" },
  },
};

export function reportStrings(locale: ReportLocale): ReportStrings {
  return locale === "en" ? EN : ES;
}

export function resolveLocale(raw: string | undefined): ReportLocale {
  return raw === "en" ? "en" : "es";
}
